apiVersion: v2
name: spawnr
description: A Kubernetes job manager for creating jobs from deployments
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - kubernetes
  - jobs
  - deployments
  - management
home: https://github.com/your-org/spawnr
sources:
  - https://github.com/your-org/spawnr
maintainers:
  - name: Your Name
    email: your.email@example.com
